# Generated by Django 5.1 on 2024-08-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tg_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="telegram.telegramuser",
            ),
        ),
    ]
