# Generated by Django 5.1 on 2024-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_account_tg_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="about_anime",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
